"""add member table

Revision ID: 084a8e1637e0
Revises: 0001_create_user
Create Date: 2026-09-21 12:03:49.452215

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "084a8e1637e0"
down_revision: str | None = "0001_create_user"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nickname", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_member_id"), "member", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_member_id"), table_name="member")
    op.drop_table("member")
    # ### end Alembic commands ###
