"""add audit timestamps, drop redundant id indexes, server default is_active

Revision ID: 98e2f7f00232
Revises: 084a8e1637e0
Create Date: 2026-09-22 13:43:41.632531

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "98e2f7f00232"
down_revision: str | None = "084a8e1637e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member",
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
    )
    op.add_column(
        "member",
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
    )
    op.alter_column(
        "member",
        "is_active",
        existing_type=sa.Boolean(),
        server_default=sa.true(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_member_id"), table_name="member")
    op.add_column(
        "user",
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
    )
    op.add_column(
        "user",
        sa.Column("updated_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
    )
    op.alter_column(
        "user",
        "is_active",
        existing_type=sa.Boolean(),
        server_default=sa.true(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_user_id"), table_name="user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.alter_column(
        "user",
        "is_active",
        existing_type=sa.Boolean(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.create_index(op.f("ix_member_id"), "member", ["id"], unique=False)
    op.alter_column(
        "member",
        "is_active",
        existing_type=sa.Boolean(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_column("member", "updated_at")
    op.drop_column("member", "created_at")
    # ### end Alembic commands ###
