"""add soft delete

Revision ID: 9f7752de540d
Revises: 98e2f7f00232
Create Date: 2026-09-22 14:20:49.206626

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9f7752de540d"
down_revision: str | None = "98e2f7f00232"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("member", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_member_deleted_at"), "member", ["deleted_at"], unique=False)
    op.add_column("user", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_user_deleted_at"), "user", ["deleted_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_deleted_at"), table_name="user")
    op.drop_column("user", "deleted_at")
    op.drop_index(op.f("ix_member_deleted_at"), table_name="member")
    op.drop_column("member", "deleted_at")
    # ### end Alembic commands ###
